# Generated by Django 2.2.5 on 2020-07-21 08:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=400)),
                ('curreny', models.IntegerField(choices=[(1, 'USD'), (2, 'INR')], default=1)),
                ('duration', models.IntegerField(choices=[(1, 'month'), (2, '6 month'), (3, '9 month'), (4, 'year')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UsersDetails',
            fields=[
                ('cust_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('sub_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('sub_status', models.IntegerField(choices=[(1, 'Active'), (2, 'trail'), (3, 'trai_end'), (4, 'past_due'), (5, 'unpaid'), (6, 'cancel'), (7, 'incomplete'), (8, 'incomplete_expired')], default=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_end_At', models.DateTimeField(default=datetime.datetime(2020, 8, 20, 8, 6, 42, 551081, tzinfo=utc))),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcriptions.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
