# Generated by Django 2.2.5 on 2020-07-21 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subcriptions', '0002_auto_20200721_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_end_At',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 12, 32, 15, 621694, tzinfo=utc)),
        ),
    ]
