# Generated by Django 2.2.5 on 2020-07-21 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subcriptions', '0004_auto_20200721_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='current_end_At',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 17, 30, 17, 217671, tzinfo=utc)),
        ),
    ]
