# Generated by Django 2.2.5 on 2020-07-22 08:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subcriptions', '0005_auto_20200721_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='current_period_start',
            new_name='current_start_at',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_end_At',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 8, 21, 10, 506997, tzinfo=utc)),
        ),
    ]
